apiVersion: apps/v1
kind: Deployment
metadata: 
  name: app-test
  labels:
    app: app-testing
spec:
  selector:
    matchLabels:
      app: app-testing
  template:
    metadata:
      name: app-test
      labels:
        app: app-testing
    spec:
      containers:
      - image: safwanseban/k8stesting:3.0.0
        imagePullPolicy: IfNotPresent
        name: app-kub
        ports:
        - containerPort: 8080 
        envFrom:
          - secretRef:
              name: postgres-secret


