# apiVersion: v1
# kind: Service
# metadata: 
#   name: postgres-service
# spec:
#   type: NodePort
#   selector: 
  
#     app: postgress-dp
#   ports:
#   - port: 5432

apiVersion: v1                                      # API version
kind: Service                                       # Type of kubernetes resource 
metadata:
  name: postgres-service                          # Name of the resource
  labels:                                           # Labels that will be applied to the resource
    app: postgres-service
spec:
  type: NodePort
  ports:
    - port: 5432
  selector:                                         # Selects any Pod with labels `app=fullstack-postgres,tier=postgres`
    app: postgress-dp
    tier: postgres



