apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvcnew
  labels:
    app: postgress-dp
spec:                                         # Access mode and resource limits
  storageClassName: pv-postgres                    # Request a certain storage class
  accessModes:
    - ReadWriteMany                           # ReadWriteMany means the volume can be mounted as read-write by many Nodes
  resources:
    requests:
      storage: 5Gi
