apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pvnew
  labels: 
    type: local
    app: postgress-dp
spec:
  storageClassName: pv-postgres
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
  persistentVolumeReclaimPolicy: Retain