# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: postgres-deployment
#   labels:
#     app: postgres
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: postgres
#   template:
#     metadata:
#       labels:
#         app: postgres
#     spec:
#       containers:
#       - image: postgres:latest
#         name: postgres
#         imagePullPolicy: "IfNotPresent"
#         ports:
#         - containerPort: 5432 
#         envFrom:                                # Get the environmental variables from a secret file whose name is "postgres-secret" 
#             - secretRef:
#                 name: postgres-secret
            
#         volumeMounts:
#         - mountPath: /var/lib/postgresql/data
#           name: postgres-persistent-storage
#       volumes:                                      # A PersistentVolume is mounted as a volume to the Pod 
#         - name: postgres-persistent-storage
#           persistentVolumeClaim:
#             claimName: postgres-pvc  
#         # envFrom:                                # Get the environmental variables from a secret file whose name is "postgres-secret" 
#         #   - secretRef:
#         #       name: postgres-secret
            


apiVersion: apps/v1
kind: Deployment                                # Type of the kubernetes resource
metadata:
  name: postgres-deployment                       # Name of the deployment
  labels:                                        # Labels applied to this deployment 
    app: postgress-dp
spec:
  selector:
    matchLabels:                                  # This deployment applies to the Pods matching the specified labels
      app: postgress-dp
      tier: postgres
  template:                                       # Template for the Pods in this deployment
    metadata:
      labels:                                     # Labels to be applied to the Pods in this deployment
        app: postgress-dp
        tier: postgres
    spec:                                         # The spec for the containers that will be run inside the Pods in this deployment
      containers:
        - image: postgres:latest                  # The container image
          name: postgres
          imagePullPolicy: "IfNotPresent"
          envFrom:                                # Get the environmental variables from a secret file whose name is "postgres-secret" 
            - secretRef:
                name: postgres-secret
            
          ports:
            - containerPort: 5432                   # The port that the container exposes 
              name: postgres
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-persistent-storage     # This name should match the name specified in `volumes.name`
      volumes:                                      # A PersistentVolume is mounted as a volume to the Pod 
        - name: postgres-persistent-storage
          persistentVolumeClaim:
            claimName: postgres-pvcnew